
apiVersion: v1
kind: Service
metadata:
  labels:
    app: udagram-frontend
  name: udagram-frontend
spec:
  ports:
  - name: http
    port: 8100
  - name: external
    port: 80
    targetPort: 8100
  - name: "https"
    port: 443
    targetPort: 8100
    protocol: "TCP"
  selector:
    app: udagram-frontend