
apiVersion: v1
kind: Service
metadata:
  labels:
    app: udagram-frontend
  name: udagram-frontend
spec:
  ports:
  - name: "8100"
    port: 8100
    targetPort: 8100
    protocol: "TCP"
  selector:
    app: udagram-frontend
