apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-proxy
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverse-proxy
  template:
    metadata:
      labels:
        app: reverse-proxy
        service: reverseproxy
    spec:
      containers:
      - image: folakemisola/udagram-reverseproxy:v1
        name: reverseproxy
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "20Mi"
            cpu: "50m"
          limits:
            memory: "54Mi"
            cpu: "100m"       
        ports:
        - containerPort: 8080
      restartPolicy: Always


