apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-proxy
  labels:
    service: reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reverse-proxy
  template:
    metadata:
      labels:
        app: reverse-proxy
        service: reverseproxy
    spec:
      containers:
      - image: folakemisola/udagram-reverseproxy:v1
        name: reverseproxy
        imagePullPolicy: Always          
        resources:
          limits:
            cpu: 200m
            memory: 204Mi
          requests:
            cpu: 50m
            memory: 102Mi   
        ports:
        - containerPort: 8080
      restartPolicy: Always


